cli_args:
- command2
exit_code: 1
output: "\n\n  RAN: /app/python-clak/tests/features/features_examples/demo108_exceptions.py\
  \ command2\n\n  STDOUT:\nManipulated error: Custom exception\n\n\n  STDERR:\n"
